const config = require('../../config')

const pluginConfig = {
    name: 'fakechat',
    alias: ['fc', 'fakewa', 'fakemsg'],
    category: 'fun',
    description: 'Generate fake WhatsApp chat',
    usage: '.fakechat @user | pesan',
    example: '.fakechat @user | Kamu ganteng banget!',
    isOwner: false,
    isPremium: false,
    isGroup: false,
    isPrivate: false,
    cooldown: 10,
    energi: 1,
    isEnabled: true
}

async function handler(m, { sock }) {
    const input = m.fullArgs?.trim() || m.text?.trim()
    
    if (!input || !input.includes('|')) {
        return m.reply(
            `💬 *ғᴀᴋᴇ ᴄʜᴀᴛ*\n\n` +
            `> Generate fake WhatsApp chat!\n\n` +
            `╭┈┈⬡「 📋 *ғᴏʀᴍᴀᴛ* 」\n` +
            `┃ .fakechat @user | pesan\n` +
            `╰┈┈┈┈┈┈┈┈⬡\n\n` +
            `*Contoh:*\n` +
            `> .fakechat @user | Kamu ganteng!\n` +
            `> .fakechat 628xxx | Hai sayang 💕\n\n` +
            `*Multi pesan:*\n` +
            `> .fakechat @user | pesan1 ; pesan2 ; pesan3`
        )
    }
    
    let target = m.mentionedJid?.[0] || m.quoted?.sender
    let messagesPart = ''
    
    const parts = input.split('|')
    if (parts.length < 2) {
        return m.reply(`❌ Format salah! Gunakan: .fakechat @user | pesan`)
    }
    
    const targetPart = parts[0].trim()
    messagesPart = parts.slice(1).join('|').trim()
    
    if (!target) {
        const numMatch = targetPart.match(/(\d{10,15})/)
        if (numMatch) {
            target = numMatch[1] + '@s.whatsapp.net'
        }
    }
    
    if (!target) {
        return m.reply(`❌ Target tidak valid! Tag user atau masukkan nomor.`)
    }
    
    if (!messagesPart) {
        return m.reply(`❌ Pesan tidak boleh kosong!`)
    }
    
    const messages = messagesPart.split(';').map(msg => msg.trim()).filter(Boolean)
    
    if (messages.length === 0) {
        return m.reply(`❌ Pesan tidak boleh kosong!`)
    }
    
    if (messages.length > 10) {
        return m.reply(`❌ Maksimal 10 pesan!`)
    }
    
    let targetName = ''
    try {
        const contact = await sock.onWhatsApp(target.split('@')[0])
        if (contact?.[0]?.exists) {
            targetName = target.split('@')[0]
        }
    } catch {}
    
    if (!targetName) {
        targetName = target.split('@')[0]
    }
    
    let ppUrl = null
    try {
        ppUrl = await sock.profilePictureUrl(target, 'image')
    } catch {}
    
    const moment = require('moment-timezone')
    const now = moment().tz('Asia/Jakarta')
    const timeStr = now.format('HH:mm')
    
    let chatText = `╭━━━━━━━━━━━━━━━━━╮\n`
    chatText += `┃  💬 *ᴡʜᴀᴛsᴀᴘᴘ ᴄʜᴀᴛ*\n`
    chatText += `╰━━━━━━━━━━━━━━━━━╯\n\n`
    chatText += `╭┈┈⬡「 👤 *${targetName}* 」\n`
    chatText += `┃ 📱 +${target.split('@')[0]}\n`
    chatText += `┃ 🟢 Online\n`
    chatText += `╰┈┈┈┈┈┈┈┈⬡\n\n`
    
    chatText += `╭─────────────────╮\n`
    
    for (let i = 0; i < messages.length; i++) {
        const msg = messages[i]
        const isFromTarget = i % 2 === 0
        const msgTime = moment(now).add(i, 'minutes')
        const msgTimeStr = msgTime.format('HH:mm')
        
        if (isFromTarget) {
            chatText += `│ ┌──────────────┐\n`
            chatText += `│ │ ${msg}\n`
            chatText += `│ │        ${msgTimeStr} ✓✓\n`
            chatText += `│ └──────────────┘\n`
        } else {
            chatText += `│        ┌──────────────┐\n`
            chatText += `│        │ ${msg}\n`
            chatText += `│        │        ${msgTimeStr} ✓✓\n`
            chatText += `│        └──────────────┘\n`
        }
    }
    
    chatText += `╰─────────────────╯\n\n`
    chatText += `> 📅 ${now.format('DD/MM/YYYY')}\n`
    chatText += `> _Generated by ${config.bot?.name || 'Ourin-AI'}_`
    
    const saluranId = config.saluran?.id || '120363401718869058@newsletter'
    const saluranName = config.saluran?.name || config.bot?.name || 'Ourin-AI'
    
    const contextInfo = {
        forwardingScore: 9999,
        isForwarded: true,
        forwardedNewsletterMessageInfo: {
            newsletterJid: saluranId,
            newsletterName: saluranName,
            serverMessageId: 127
        }
    }
    
    if (ppUrl) {
        contextInfo.externalAdReply = {
            title: `Chat dengan ${targetName}`,
            body: messages[0].slice(0, 50),
            thumbnailUrl: ppUrl,
            mediaType: 1,
            renderLargerThumbnail: true
        }
    }
    
    await sock.sendMessage(m.chat, {
        text: chatText,
        contextInfo
    }, { quoted: m })
}

module.exports = {
    config: pluginConfig,
    handler
}
